version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: api_to_automate
    volumes:
      - /tmp/mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  rustapp:
    image: backend:latest
    container_name: rustapp_backend
    env_file:
      - ./.env
    networks:
      - app-network
  rustapp_front:
    image: frontend:latest
    container_name: rustapp_front
    networks:
      - app-network

  web:
    image: nginx:latest
    volumes:
      - ./infrastructure:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge