apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
      #tu zaczyna sie blueprint podów. Od template a w specyfikacji jego kontenery z danymi
  template:
    metadata:
      labels:
        app: mongo
    spec:
      #kontenery i ich definicje
      containers:
        - name: mongodb
          image: mongo:5.0
          ports:
            - containerPort: 27017
              #enviroment variables brane z mongo-secret za pomoca valueFrom i secretKeyRef:
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017